version: '3.4'

services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  orderservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  customerservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

